### ISSUE TITLE
[CheckboxInput] Unable to navigate through Tab key in toggle mode with tabindex

### ISSUE THREAD

**Issue by antoineblancke** [AxaGuilDEv/react-toolkit#582]
### Issue and Steps to Reproduce

Hi,
With the CheckboxInput component in toggle mode, the navigation through "Tab" key does not seem to be working as the input is hidden behind the rendered Toggle button. 

It seems to be working when I set the property "visibility" to "visible" without any bugs in the UI.

#### Versions
^1.3.4

#### Expected
Navigation with Tab key focusing on the toggle button.

#### Actual
Navigation with Tab key is not focusing on the toggle button.

#### Additional Details
Tested on Chrome 78/Firefox 74

- Installed packages
@axa-fr/react-toolkit-all
@axa-fr/react-toolkit-form-input-checkbox

**Comment by antoineblancke** [comment]
Not sure that modifying the visibility to visible is a good thing though.

**Comment by samuel-gomez-axa** [comment]
Thank you Antoine for the issue :)
this component does not yet manage keyboard navigation (for all modes). This is a very good improvement proposal, especially for accessibility. We have to ask the UX Designers to define the graphic behavior for the focus of the field

**Comment by samuel-gomez-axa** [comment]
these lines should fix the issue : 
```css
.af-form__radio-custom {
  .af-form__input-radio {
    visibility: inherit;
  }
}
.af-form__checkbox-toggle {
  .af-form__input-checkbox {
    visibility: inherit;
    &:focus + .af-form__label {
      box-shadow: 0 0 5px $color-axa;
    }
  }
}
```
